[package]
name = "micrograd"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = { path = "/Users/vova/work/workspace/petgraph" }
uuid = { version = "1.13.1", features = ["v4"] }

[dev-dependencies]
assert_approx_eq = "1.1.0"
